services:
  vue-demo-prod:
    build:
      context: .
      args:
        - VITE_APP_API_URL=${VITE_APP_API_URL}
    container_name: vue-demo-prod
    ports:
      - "8081:8080" # Porta 8081 per evitare conflitti con lo sviluppo (8080)
    env_file:
      - .env.production
    restart: unless-stopped
    # In produzione costruiamo l'app e la serviamo con il comando 'preview' di Vite
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 8080"
