services:
  vue-demo:
    build: .
    container_name: vue-demo
    ports:
      - "8080:8080"  # Porta di Vite
    volumes:
      - .:/app  # Monta la directory corrente in `/app`
      - /app/node_modules  # Volume anonimo per node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    restart: unless-stopped
    command: sh -c "npm install && npx playwright install chromium && npm run dev"  # Sincronizza npm, browser e avvia Vite
